Algoritmo "saudacao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Darlan MAchado
// Descrição   : Algoritmo que apresenta uma mensagem de saudação
// Data atual  : 28/06/2021
Var
// Seção de Declarações das variáveis

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   escreva("Seja bem vindo ao curso de lógica de programação e linguagem c")


Fimalgoritmo